{% set version = '1.1.2' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-cutpointr
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/cutpointr_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/cutpointr/cutpointr_{{ version }}.tar.gz
  sha256: 3280ecedb81e373629b20d2186285f86397a28e7ef684ac04e700d0d8180b6e3

build:
  merge_build_host: True  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'           # [win]

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-rcpp >=0.12.12
    - r-dplyr >=0.8.0
    - r-foreach >=1.4.3
    - r-ggplot2 >=3.0.0
    - r-gridextra >=2.2.1
    - r-purrr >=0.3.0
    - r-rlang >=0.4.0
    - r-tibble >=3.0.0
    - r-tidyr >=1.0.0
    - r-tidyselect >=1.1.0
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-rcpp >=0.12.12
    - r-dplyr >=0.8.0
    - r-foreach >=1.4.3
    - r-ggplot2 >=3.0.0
    - r-gridextra >=2.2.1
    - r-purrr >=0.3.0
    - r-rlang >=0.4.0
    - r-tibble >=3.0.0
    - r-tidyr >=1.0.0
    - r-tidyselect >=1.1.0

test:
  commands:
    - $R -e "library('cutpointr')"           # [not win]
    - "\"%R%\" -e \"library('cutpointr')\""  # [win]

about:
  home: https://github.com/thie1e/cutpointr
  license: GPL-3.0-only
  summary: Estimate cutpoints that optimize a specified metric in binary classification tasks
    and validate performance using bootstrapping. Some methods for more robust cutpoint
    estimation are supported, e.g. a parametric method assuming normal distributions,
    bootstrapped cutpoints, and smoothing of the metric values per cutpoint using Generalized
    Additive Models. Various plotting functions are included. For an overview of the
    package see Thiele and Hirschfeld (2021) <doi:10.18637/jss.v098.i11>.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
